"""Structural contracts shared by local and PostgreSQL service implementations."""
from __future__ import annotations

import builtins
from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from .operations import ExecutionJob, MetricsSnapshot, OperationalEvent
from .productization import (
    ArtifactRecord,
    KnowledgeDocument,
    StrategySpec,
    ToolDefinition,
    Workspace,
)

type WorkspaceList = builtins.list[Workspace]
type ArtifactList = builtins.list[ArtifactRecord]
type KnowledgeList = builtins.list[KnowledgeDocument]
type ToolList = builtins.list[ToolDefinition]
type EventList = builtins.list[OperationalEvent]


class WorkspaceService(Protocol):
    def submit(self, workspace: Workspace, idempotency_key: str | None = None) -> Workspace: ...
    def get(self, workspace_id: UUID) -> Workspace: ...
    def list(self, include_archived: bool = False) -> WorkspaceList: ...
    def update(self, workspace_id: UUID, expected_version: int, *, name: str, product_goal: str, priority: int, strategies: Sequence[StrategySpec]) -> Workspace: ...
    def archive(self, workspace_id: UUID, expected_version: int) -> Workspace: ...
    def restore(self, workspace_id: UUID, expected_version: int) -> Workspace: ...
    def delete(self, workspace_id: UUID, expected_version: int) -> None: ...


class ArtifactService(Protocol):
    def put(self, artifact: ArtifactRecord) -> ArtifactRecord: ...
    def list(self, workspace_id: UUID) -> ArtifactList: ...


class KnowledgeService(Protocol):
    def upsert(self, document: KnowledgeDocument) -> KnowledgeDocument: ...
    def search(self, query: str, limit: int = 10, workspace_id: UUID | None = None) -> KnowledgeList: ...


class ToolService(Protocol):
    def register(self, tool: ToolDefinition) -> None: ...
    def list(self) -> ToolList: ...


class ExecutionService(Protocol):
    def enqueue(self, workflow_id: UUID, workspace_id: UUID, stage: str, idempotency_key: str, max_attempts: int = 3) -> ExecutionJob: ...
    def claim(self, worker_id: str) -> ExecutionJob | None: ...
    def heartbeat(self, job_id: UUID, worker_id: str) -> ExecutionJob: ...
    def complete(self, job_id: UUID, worker_id: str) -> ExecutionJob: ...
    def fail(self, job_id: UUID, worker_id: str, error: str) -> ExecutionJob: ...
    def cancel(self, job_id: UUID) -> ExecutionJob: ...
    def snapshot(self) -> MetricsSnapshot: ...


class ObservabilityService(Protocol):
    def record(self, event: OperationalEvent) -> OperationalEvent: ...
    def query(self, workflow_id: UUID | None = None, workspace_id: UUID | None = None, job_id: UUID | None = None, limit: int = 100) -> EventList: ...
