"""Structural contracts shared by local and PostgreSQL service implementations."""
from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from .operations import ExecutionJob, MetricsSnapshot, OperationalEvent
from .productization import (
    ArtifactRecord,
    KnowledgeDocument,
    StrategySpec,
    ToolDefinition,
    Workspace,
)


class WorkspaceService(Protocol):
    def submit(self, workspace: Workspace, idempotency_key: str | None = None) -> Workspace: ...
    def get(self, workspace_id: UUID) -> Workspace: ...
    def list(self, include_archived: bool = False) -> Sequence[Workspace]: ...
    def update(self, workspace_id: UUID, expected_version: int, *, name: str, product_goal: str, priority: int, strategies: Sequence[StrategySpec]) -> Workspace: ...
    def archive(self, workspace_id: UUID, expected_version: int) -> Workspace: ...
    def restore(self, workspace_id: UUID, expected_version: int) -> Workspace: ...
    def delete(self, workspace_id: UUID, expected_version: int) -> None: ...


class ArtifactService(Protocol):
    def put(self, artifact: ArtifactRecord) -> ArtifactRecord: ...
    def list(self, workspace_id: UUID) -> Sequence[ArtifactRecord]: ...


class KnowledgeService(Protocol):
    def upsert(self, document: KnowledgeDocument) -> KnowledgeDocument: ...
    def search(self, query: str, limit: int = 10) -> Sequence[KnowledgeDocument]: ...


class ToolService(Protocol):
    def register(self, tool: ToolDefinition) -> None: ...
    def get(self, name: str) -> ToolDefinition: ...
    def list(self) -> Sequence[ToolDefinition]: ...


class OperationsService(Protocol):
    def enqueue(self, job: ExecutionJob) -> ExecutionJob: ...
    def record_event(self, event: OperationalEvent) -> OperationalEvent: ...
    def metrics(self) -> MetricsSnapshot: ...
